/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kindredgroup.sampleevent;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Brand { 
  UNIBET, MARIA, STANJAMES  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Brand\",\"namespace\":\"com.kindredgroup.sampleevent\",\"symbols\":[\"UNIBET\",\"MARIA\",\"STANJAMES\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
