/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kindredgroup.sampleevent;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Channel { 
  WEB, PHONE, MOBILE, NATIVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Channel\",\"namespace\":\"com.kindredgroup.sampleevent\",\"symbols\":[\"WEB\",\"PHONE\",\"MOBILE\",\"NATIVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
