/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kindredgroup.sampleevent;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Country { 
  MT, UK, SJ, IT, FR, VS, FE, DK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Country\",\"namespace\":\"com.kindredgroup.sampleevent\",\"symbols\":[\"MT\",\"UK\",\"SJ\",\"IT\",\"FR\",\"VS\",\"FE\",\"DK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
