/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.kindredgroup.sampleevent;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EventGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventGroup\",\"namespace\":\"com.kindredgroup.sampleevent\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"doc\":\"Event group id.\",\"default\":0},{\"name\":\"name\",\"type\":\"string\",\"doc\":\"\",\"default\":\"\"},{\"name\":\"eventTimestamp\",\"type\":\"long\",\"doc\":\"\",\"default\":0},{\"name\":\"status\",\"type\":\"long\",\"doc\":\"\",\"default\":0},{\"name\":\"customerId\",\"type\":\"long\",\"doc\":\"Customer Id.\",\"default\":0,\"piiField\":true,\"ipAddressField\":false},{\"name\":\"internalSystemInfo\",\"type\":\"string\",\"doc\":\"Internal system info. Like, session Id.\",\"default\":\"\",\"piiField\":true,\"ipAddressField\":false},{\"name\":\"jurisdiction\",\"type\":[\"string\",{\"type\":\"enum\",\"name\":\"Country\",\"symbols\":[\"MT\",\"UK\",\"SJ\",\"IT\",\"FR\",\"VS\",\"FE\",\"DK\"]}],\"doc:\":\"Country information\"},{\"name\":\"channel\",\"type\":[\"string\",{\"type\":\"enum\",\"name\":\"Channel\",\"symbols\":[\"WEB\",\"PHONE\",\"MOBILE\",\"NATIVE\"]}],\"doc:\":\"Channel information\"},{\"name\":\"brand\",\"type\":[\"string\",{\"type\":\"enum\",\"name\":\"Brand\",\"symbols\":[\"UNIBET\",\"MARIA\",\"STANJAMES\"]}],\"doc:\":\"Brand information\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Event group id. */
  @Deprecated public long id;
  /**  */
  @Deprecated public java.lang.CharSequence name;
  /**  */
  @Deprecated public long eventTimestamp;
  /**  */
  @Deprecated public long status;
  /** Customer Id. */
  @Deprecated public long customerId;
  /** Internal system info. Like, session Id. */
  @Deprecated public java.lang.CharSequence internalSystemInfo;
  @Deprecated public java.lang.Object jurisdiction;
  @Deprecated public java.lang.Object channel;
  @Deprecated public java.lang.Object brand;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public EventGroup() {}

  /**
   * All-args constructor.
   */
  public EventGroup(java.lang.Long id, java.lang.CharSequence name, java.lang.Long eventTimestamp, java.lang.Long status, java.lang.Long customerId, java.lang.CharSequence internalSystemInfo, java.lang.Object jurisdiction, java.lang.Object channel, java.lang.Object brand) {
    this.id = id;
    this.name = name;
    this.eventTimestamp = eventTimestamp;
    this.status = status;
    this.customerId = customerId;
    this.internalSystemInfo = internalSystemInfo;
    this.jurisdiction = jurisdiction;
    this.channel = channel;
    this.brand = brand;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return eventTimestamp;
    case 3: return status;
    case 4: return customerId;
    case 5: return internalSystemInfo;
    case 6: return jurisdiction;
    case 7: return channel;
    case 8: return brand;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: eventTimestamp = (java.lang.Long)value$; break;
    case 3: status = (java.lang.Long)value$; break;
    case 4: customerId = (java.lang.Long)value$; break;
    case 5: internalSystemInfo = (java.lang.CharSequence)value$; break;
    case 6: jurisdiction = (java.lang.Object)value$; break;
    case 7: channel = (java.lang.Object)value$; break;
    case 8: brand = (java.lang.Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * Event group id.   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * Event group id.   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   *    */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   *    * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'eventTimestamp' field.
   *    */
  public java.lang.Long getEventTimestamp() {
    return eventTimestamp;
  }

  /**
   * Sets the value of the 'eventTimestamp' field.
   *    * @param value the value to set.
   */
  public void setEventTimestamp(java.lang.Long value) {
    this.eventTimestamp = value;
  }

  /**
   * Gets the value of the 'status' field.
   *    */
  public java.lang.Long getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   *    * @param value the value to set.
   */
  public void setStatus(java.lang.Long value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * Customer Id.   */
  public java.lang.Long getCustomerId() {
    return customerId;
  }

  /**
   * Sets the value of the 'customerId' field.
   * Customer Id.   * @param value the value to set.
   */
  public void setCustomerId(java.lang.Long value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'internalSystemInfo' field.
   * Internal system info. Like, session Id.   */
  public java.lang.CharSequence getInternalSystemInfo() {
    return internalSystemInfo;
  }

  /**
   * Sets the value of the 'internalSystemInfo' field.
   * Internal system info. Like, session Id.   * @param value the value to set.
   */
  public void setInternalSystemInfo(java.lang.CharSequence value) {
    this.internalSystemInfo = value;
  }

  /**
   * Gets the value of the 'jurisdiction' field.
   */
  public java.lang.Object getJurisdiction() {
    return jurisdiction;
  }

  /**
   * Sets the value of the 'jurisdiction' field.
   * @param value the value to set.
   */
  public void setJurisdiction(java.lang.Object value) {
    this.jurisdiction = value;
  }

  /**
   * Gets the value of the 'channel' field.
   */
  public java.lang.Object getChannel() {
    return channel;
  }

  /**
   * Sets the value of the 'channel' field.
   * @param value the value to set.
   */
  public void setChannel(java.lang.Object value) {
    this.channel = value;
  }

  /**
   * Gets the value of the 'brand' field.
   */
  public java.lang.Object getBrand() {
    return brand;
  }

  /**
   * Sets the value of the 'brand' field.
   * @param value the value to set.
   */
  public void setBrand(java.lang.Object value) {
    this.brand = value;
  }

  /** Creates a new EventGroup RecordBuilder */
  public static com.kindredgroup.sampleevent.EventGroup.Builder newBuilder() {
    return new com.kindredgroup.sampleevent.EventGroup.Builder();
  }
  
  /** Creates a new EventGroup RecordBuilder by copying an existing Builder */
  public static com.kindredgroup.sampleevent.EventGroup.Builder newBuilder(com.kindredgroup.sampleevent.EventGroup.Builder other) {
    return new com.kindredgroup.sampleevent.EventGroup.Builder(other);
  }
  
  /** Creates a new EventGroup RecordBuilder by copying an existing EventGroup instance */
  public static com.kindredgroup.sampleevent.EventGroup.Builder newBuilder(com.kindredgroup.sampleevent.EventGroup other) {
    return new com.kindredgroup.sampleevent.EventGroup.Builder(other);
  }
  
  /**
   * RecordBuilder for EventGroup instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventGroup>
    implements org.apache.avro.data.RecordBuilder<EventGroup> {

    private long id;
    private java.lang.CharSequence name;
    private long eventTimestamp;
    private long status;
    private long customerId;
    private java.lang.CharSequence internalSystemInfo;
    private java.lang.Object jurisdiction;
    private java.lang.Object channel;
    private java.lang.Object brand;

    /** Creates a new Builder */
    private Builder() {
      super(com.kindredgroup.sampleevent.EventGroup.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.kindredgroup.sampleevent.EventGroup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[2].schema(), other.eventTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customerId)) {
        this.customerId = data().deepCopy(fields()[4].schema(), other.customerId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.internalSystemInfo)) {
        this.internalSystemInfo = data().deepCopy(fields()[5].schema(), other.internalSystemInfo);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.jurisdiction)) {
        this.jurisdiction = data().deepCopy(fields()[6].schema(), other.jurisdiction);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.channel)) {
        this.channel = data().deepCopy(fields()[7].schema(), other.channel);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.brand)) {
        this.brand = data().deepCopy(fields()[8].schema(), other.brand);
        fieldSetFlags()[8] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EventGroup instance */
    private Builder(com.kindredgroup.sampleevent.EventGroup other) {
            super(com.kindredgroup.sampleevent.EventGroup.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTimestamp)) {
        this.eventTimestamp = data().deepCopy(fields()[2].schema(), other.eventTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customerId)) {
        this.customerId = data().deepCopy(fields()[4].schema(), other.customerId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.internalSystemInfo)) {
        this.internalSystemInfo = data().deepCopy(fields()[5].schema(), other.internalSystemInfo);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.jurisdiction)) {
        this.jurisdiction = data().deepCopy(fields()[6].schema(), other.jurisdiction);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.channel)) {
        this.channel = data().deepCopy(fields()[7].schema(), other.channel);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.brand)) {
        this.brand = data().deepCopy(fields()[8].schema(), other.brand);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Long getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'eventTimestamp' field */
    public java.lang.Long getEventTimestamp() {
      return eventTimestamp;
    }
    
    /** Sets the value of the 'eventTimestamp' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setEventTimestamp(long value) {
      validate(fields()[2], value);
      this.eventTimestamp = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'eventTimestamp' field has been set */
    public boolean hasEventTimestamp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'eventTimestamp' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearEventTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.Long getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setStatus(long value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'status' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearStatus() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'customerId' field */
    public java.lang.Long getCustomerId() {
      return customerId;
    }
    
    /** Sets the value of the 'customerId' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setCustomerId(long value) {
      validate(fields()[4], value);
      this.customerId = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'customerId' field has been set */
    public boolean hasCustomerId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'customerId' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearCustomerId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'internalSystemInfo' field */
    public java.lang.CharSequence getInternalSystemInfo() {
      return internalSystemInfo;
    }
    
    /** Sets the value of the 'internalSystemInfo' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setInternalSystemInfo(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.internalSystemInfo = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'internalSystemInfo' field has been set */
    public boolean hasInternalSystemInfo() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'internalSystemInfo' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearInternalSystemInfo() {
      internalSystemInfo = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'jurisdiction' field */
    public java.lang.Object getJurisdiction() {
      return jurisdiction;
    }
    
    /** Sets the value of the 'jurisdiction' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setJurisdiction(java.lang.Object value) {
      validate(fields()[6], value);
      this.jurisdiction = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'jurisdiction' field has been set */
    public boolean hasJurisdiction() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'jurisdiction' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearJurisdiction() {
      jurisdiction = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'channel' field */
    public java.lang.Object getChannel() {
      return channel;
    }
    
    /** Sets the value of the 'channel' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setChannel(java.lang.Object value) {
      validate(fields()[7], value);
      this.channel = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'channel' field has been set */
    public boolean hasChannel() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'channel' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearChannel() {
      channel = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'brand' field */
    public java.lang.Object getBrand() {
      return brand;
    }
    
    /** Sets the value of the 'brand' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder setBrand(java.lang.Object value) {
      validate(fields()[8], value);
      this.brand = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'brand' field has been set */
    public boolean hasBrand() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'brand' field */
    public com.kindredgroup.sampleevent.EventGroup.Builder clearBrand() {
      brand = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public EventGroup build() {
      try {
        EventGroup record = new EventGroup();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.eventTimestamp = fieldSetFlags()[2] ? this.eventTimestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (java.lang.Long) defaultValue(fields()[3]);
        record.customerId = fieldSetFlags()[4] ? this.customerId : (java.lang.Long) defaultValue(fields()[4]);
        record.internalSystemInfo = fieldSetFlags()[5] ? this.internalSystemInfo : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.jurisdiction = fieldSetFlags()[6] ? this.jurisdiction : (java.lang.Object) defaultValue(fields()[6]);
        record.channel = fieldSetFlags()[7] ? this.channel : (java.lang.Object) defaultValue(fields()[7]);
        record.brand = fieldSetFlags()[8] ? this.brand : (java.lang.Object) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
